### PR TITLE
Clean up gulpfile, fix all tests, add contributing docs to readme

### PR DESCRIPTION
**Pull request by contolini**
@dgreisen-cfpb @m3brown @imuchnik I cleaned up the gulpfile and fixed all the tests. There's now only one build task with a couple flags:
- `gulp build` processes everything in `src/` and dumps it into `dist/`.
- `gulp build --dev` moves everything from `src/` to `dist/` without processing it (JS and Less won't be minified) .
- `gulp build --watch` watches everything in `src/` and moves changed files to `dist/`. This task should be a loooot faster, processing everything in ~ 1 sec.

### CODE REVIEW

**Comment by imuchnik** [comment]
:+1:

**Comment by contolini** [comment]
:+1:

**Comment by dgreisen-cfpb** [comment]
:-1:

We had discussed checking in the dist directory so we don't need a build step for our deploy. This makes that difficult/error-prone, I think.

With two different build directories, we can git-ignore the dev directory and checkin the dist directory. The pr in devdash then ensured that nginx points to dev while developing and dist in production.

On further reflection, I think I would build to dist and dev every time we run gulp build, and get rid of devbuild (or whatever) that way we ensure both dist and dev are always up-to-date.

The alternative we had discussed is to stand up a build server in the next day, or so. But that doesn't seem like a productive use of anyone's time.

**Comment by contolini** [comment]
:+1: to your :-1: So _that's_ what dev does. Let's do a quick call.

**Pull request merged**
